name: CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Upgradeable Token CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Show Forge version
      - name: Show Forge version
        run: forge --version

      # Run Foundry formatting check
      - name: Check Forge formatting
        run: forge fmt --check

      # Run Foundry tests
      - name: Run Foundry tests
        run: forge test --gas-report


      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
